# Set to some text value if you want templated config files
# to contain a custom banner at the top of the written file
default['openstack']['key-manager']['custom_template_banner'] = '
# This file is automatically generated by Chef
# Any changes will be overwritten
'

%w(internal public admin).each do |ep_type|
  # host for openstack internal/public key-manager endpoint
  default['openstack']['endpoints'][ep_type]['key-manager']['host'] = '127.0.0.1'
  # scheme for openstack internal/public key-manager endpoint
  default['openstack']['endpoints'][ep_type]['key-manager']['scheme'] = 'http'
  # port for openstack internal/public key-manager endpoint
  default['openstack']['endpoints'][ep_type]['key-manager']['port'] = '9311'
end
default['openstack']['bind_service']['all']['key-manager']['host'] = '127.0.0.1'
default['openstack']['bind_service']['all']['key-manager']['port'] = '9311'

default['openstack']['key-manager']['user'] = 'barbican'
default['openstack']['key-manager']['group'] = 'barbican'

default['openstack']['key-manager']['service_user'] = 'barbican'
default['openstack']['key-manager']['service_role'] = 'service'
default['openstack']['key-manager']['service_name'] = 'barbican'
default['openstack']['key-manager']['service_type'] = 'key-manager'
default['openstack']['key-manager']['region'] = node['openstack']['region']

# platform defaults TODO: fill debian packages
case node['platform_family']
when 'debian'
  # platform specific package and service name options
  default['openstack']['key-manager']['platform'] = {
      'memcache_python_packages' => ['python-memcached'],
      'barbican_api_packages' => %w(),
      'barbican_api_service' => '',
      'package_options' => '',
  }
when 'fedora', 'rhel' # :pragma-foodcritic: ~FC024 - won't fix this
  # platform specific package and service name options
  default['openstack']['key-manager']['platform'] = {
      'memcache_python_packages' => ['python-memcache'],
      'barbican_api_packages' => %w(openstack-barbican-api),
      'barbican_api_service' => 'openstack-barbican-api',
      'barbican_client_packages' => %w(python-barbicanclient),
      'package_overrides' => '',
  }
end

# logging
default['openstack']['key-manager']['syslog']['use'] = true

# ssl
default['openstack']['key-manager']['ssl']['enabled'] = false
default['openstack']['key-manager']['ssl']['certfile'] = ''
default['openstack']['key-manager']['ssl']['chainfile'] = ''
default['openstack']['key-manager']['ssl']['keyfile'] = ''
default['openstack']['key-manager']['ssl']['ca_certs_path'] = ''
default['openstack']['key-manager']['ssl']['cert_required'] = ''
default['openstack']['key-manager']['ssl']['protocol'] = ''
default['openstack']['key-manager']['ssl']['ciphers'] = ''
